### ISSUE TITLE
No match on the number of head orientations and the number of frames

### ISSUE THREAD

**Issue by HaoranLv** [Archer-Tatsu/head-tracking#2] opened 2019-09-19 08:48 UTC
Hello, I recently tried to quote your dataset, but found that the number of video frames does not match the number of head orientations when viewing. How often do you collect the head orientation?

**Comment by Archer-Tatsu** [comment] 2020-03-26 12:03
Duplicate of #1

**Closed as completed by Archer-Tatsu** 2020-03-26 12:03 UTC
Labels: duplicate
